set(SOURCES
	src/InfiniteAmmo.h
	src/InfiniteAmmo.cpp
	src/Hooks.h
	src/Hooks.cpp
	src/Scripts.h
	src/Scripts.cpp
	src/Events.h
	src/Events.cpp
	src/Settings.h
	src/Settings.cpp
	src/Utils.h
	src/Utils.cpp
	src/PCH.h
	src/main.cpp
)